config/routes.rb
Rails.application.routes.draw do
  # namespaceで区切られているものはroutesフォルダーに切り分けて、routes.rbが膨らまないようにする。
  def draw(name)
    instance_eval(File.read(Rails.root.join("config/routes/#{name}.rb")))
  end

  # APP側とAPI側でWords一覧の種類が被っているので、concernで切り出している。
  concern :words_index do
    collection do
      get "index_latest_order"
      get "index_random_order"
      get "index_scoped_follow_users"
      get "search"
    end
  end

  draw :admin
  draw :api

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "root#index"

  resources :words, only: %i[new create show destroy], concerns: :words_index

  resources :users, only: %i[show], constraints: {id: /\d+/} do
    scope module: :users do
      resources :favorites, only: %i[index]
      resources :follow_relations, only: %i[index]
    end
  end

  # お問い合わせフォームの実装
  resource :contact, only: %i[show]

  namespace :pages do
    # プライバシーポリシーに使うルーティング
    get :privacy_policy

    # 利用規約に使うルーティング
    get :terms_of_service
  end

  # 仮会員に送られるメールのURLから遷移する際、getメソッドしか使えないため明示的にgetメソッドにしている
  get "users/create", to: "users#create"
  resource :signup, only: %i[new create], controller: :provisional_users, path_names: {new: ""}
  resource :user_profile, only: %i[new create edit update]

  # ログイン・ログアウト処理に使うルーティング
  resource :login, only: %i[new create], controller: :sessions, path_names: {new: ""}
  resource :logout, controller: :sessions, only: %i[destroy]

  namespace :user do
    resource :email, only: %i[edit update]
    resource :password, only: %i[edit update]
    resource :mypage, only: %i[show]
    resource :password_reissue_token, only: %i[new create]
    resource :password_reissue, only: %i[new create]
  end

  # letter_openerのgemを利用するroutingで開発中にrailsから送信されたメールを確認するためのもの
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  # いずれのルーティング定義にも当てはまらない場合にエラー画面を表示
  get "*not_found", to: "exceptions#routing_error" unless Rails.env.development?
end

app/views/layouts/partials/_google_analytics.html.slim
- if ENV["GOOGLE_ANALYTICS_ENABLED"].present?
  script[src="https://www.googletagmanager.com/gtag/js?id=UA-123831279-1" async=""]
  javascript:
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-123831279-1');

app/views/layouts/partials/_header.html.slim
header#header.header
  .header-side-element.header-left-element
    - if visible_return_link
      / 戻るボタン
      i.fas.fa-arrow-left.return-btn onclick="javascript:window.history.back(-1);return false;"

  .header-center-element
    / Headerタイトル
    - if header_title.present?
      h1.header-title
        = header_title
    - elsif header_center_element.present?
      = header_center_element

  .header-side-element.header-right-element
    - if header_right_element.present?
      = header_right_element

  - if logged_in? && !hide_nav
    nav#nav.nav
      = link_to index_latest_order_words_path, class: "nav-link #{active_nav_index == '0' ? 'active' : ''}" do
        .nav-link-text
          | 辞書
        i.fas.fa-book-open

      = link_to search_words_path, class: "nav-link #{active_nav_index == '1' ? 'active' : ''}" do
        .nav-link-text
          | 検索
        i.fas.fa-search

      = link_to user_mypage_path, class: "nav-link #{active_nav_index == '2' ? 'active' : ''}" do
        .nav-link-text
          | マイページ
        i.fas.fa-user-alt

.mobile-header-space

- if logged_in? && !hide_nav
  .mobile-nav-space